/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vicky
 */
public class AddBookForm extends javax.swing.JFrame {

    /**
     * Creates new form AddBookForm
     */
    public AddBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddBook = new javax.swing.JPanel();
        jLabelBookID = new javax.swing.JLabel();
        jLabelEnterBookDetails = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelBookTItle = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelStoreLocation = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldStoreLocation = new javax.swing.JTextField();
        jTextFieldBookTitle = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldBookID = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jTextFieldAuthor = new javax.swing.JTextField();
        jLabelPublisher = new javax.swing.JLabel();
        jTextFieldPublisher = new javax.swing.JTextField();
        jLabelCategory = new javax.swing.JLabel();
        jTextFieldCategory = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAddBook.setBackground(new java.awt.Color(0, 0, 0));

        jLabelBookID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelBookID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBookID.setText("Book ID : ");

        jLabelEnterBookDetails.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelEnterBookDetails.setForeground(new java.awt.Color(255, 255, 0));
        jLabelEnterBookDetails.setText("Enter Book Details");

        jLabelPrice.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setText("Price (RM) :");

        jLabelQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantity.setText("Quantity :");

        jLabelBookTItle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelBookTItle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBookTItle.setText("Book Title :");

        jLabelAuthor.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelAuthor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAuthor.setText("Author :");

        jLabelStoreLocation.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelStoreLocation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStoreLocation.setText("Store Location :");

        jTextFieldQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldStoreLocation.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldBookTitle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldPrice.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldBookID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jLabelYear.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Year :");

        jTextFieldYear.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldAuthor.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jLabelPublisher.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelPublisher.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPublisher.setText("Publisher :");

        jTextFieldPublisher.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jLabelCategory.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelCategory.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategory.setText("Category/Genre :");

        jTextFieldCategory.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jButtonEnter.setBackground(new java.awt.Color(0, 0, 204));
        jButtonEnter.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(0, 255, 255));
        jButtonEnter.setText("ENTER");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(153, 0, 51));
        jButtonBack.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 204, 51));
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddBookLayout = new javax.swing.GroupLayout(jPanelAddBook);
        jPanelAddBook.setLayout(jPanelAddBookLayout);
        jPanelAddBookLayout.setHorizontalGroup(
            jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddBookLayout.createSequentialGroup()
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addComponent(jLabelBookTItle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBookTitle))
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddBookLayout.createSequentialGroup()
                                .addComponent(jLabelPrice)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)
                                .addComponent(jLabelYear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAddBookLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEnterBookDetails)
                                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                                        .addComponent(jLabelBookID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBookID)))
                                .addGap(108, 108, 108)
                                .addComponent(jLabelQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(151, 151, 151))
            .addGroup(jPanelAddBookLayout.createSequentialGroup()
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addComponent(jLabelStoreLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStoreLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addComponent(jLabelAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addComponent(jLabelPublisher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddBookLayout.createSequentialGroup()
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addComponent(jLabelCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCategory))
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(392, 392, 392)
                        .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(70, 70, 70))
        );
        jPanelAddBookLayout.setVerticalGroup(
            jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEnterBookDetails)
                .addGap(18, 18, 18)
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddBookLayout.createSequentialGroup()
                        .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBookID)
                            .addComponent(jLabelQuantity)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBookTItle)
                            .addComponent(jTextFieldBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrice)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelYear))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStoreLocation)
                    .addComponent(jTextFieldStoreLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuthor)
                    .addComponent(jTextFieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPublisher)
                    .addComponent(jTextFieldPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategory)
                    .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanelAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
                FunctionForm form = new FunctionForm();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        Book book = new Book( Integer.valueOf(jTextFieldBookID.getText()), jTextFieldBookTitle.getText(), Integer.valueOf(jTextFieldQuantity.getText()), Float.valueOf(jTextFieldPrice.getText()), jTextFieldStoreLocation.getText(), jTextFieldAuthor.getText(), jTextFieldPublisher.getText(), jTextFieldCategory.getText(), Integer.valueOf(jTextFieldYear.getText()));
        if(book.addBook()) {
            JOptionPane.showMessageDialog(rootPane, "Succesefully added new book", "Added a new book", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Failed to added new book", "Failed new book", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelBookID;
    private javax.swing.JLabel jLabelBookTItle;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelEnterBookDetails;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPublisher;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStoreLocation;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelAddBook;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldBookID;
    private javax.swing.JTextField jTextFieldBookTitle;
    private javax.swing.JTextField jTextFieldCategory;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldPublisher;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldStoreLocation;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
