/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vicky
 */
public class AddStationeryForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStationeryForm
     */
    public AddStationeryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneAddST = new javax.swing.JPanel();
        jPanelAddStationery = new javax.swing.JPanel();
        jLabelStationeryID = new javax.swing.JLabel();
        jLabelEnterStationeryDetails = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelStoreLocation = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldStoreLocation = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldStationeryID = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jLabelManufacturer = new javax.swing.JLabel();
        jTextFieldManufacturer = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAddStationery.setBackground(new java.awt.Color(0, 0, 0));

        jLabelStationeryID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelStationeryID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStationeryID.setText("Stationery ID : ");

        jLabelEnterStationeryDetails.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelEnterStationeryDetails.setForeground(new java.awt.Color(255, 255, 0));
        jLabelEnterStationeryDetails.setText("Enter Stationery Details");

        jLabelPrice.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setText("Price (RM) :");

        jLabelQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantity.setText("Quantity :");

        jLabelName.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Name :");

        jLabelType.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType.setText("Type :");

        jLabelStoreLocation.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelStoreLocation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStoreLocation.setText("Store Location :");

        jTextFieldQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldStoreLocation.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldName.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldPrice.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldStationeryID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTextFieldType.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jLabelManufacturer.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManufacturer.setText("Manufacturer :");

        jTextFieldManufacturer.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jButtonEnter.setBackground(new java.awt.Color(0, 51, 255));
        jButtonEnter.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(0, 255, 255));
        jButtonEnter.setText("ENTER");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(153, 0, 51));
        jButtonBack.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 204, 51));
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddStationeryLayout = new javax.swing.GroupLayout(jPanelAddStationery);
        jPanelAddStationery.setLayout(jPanelAddStationeryLayout);
        jPanelAddStationeryLayout.setHorizontalGroup(
            jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName))
                    .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                        .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                                .addComponent(jLabelPrice)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEnterStationeryDetails)
                                    .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                                        .addComponent(jLabelStationeryID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldStationeryID)))
                                .addGap(108, 108, 108)
                                .addComponent(jLabelQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(151, 151, 151))
            .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                        .addComponent(jLabelStoreLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStoreLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                        .addComponent(jLabelType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                        .addComponent(jLabelManufacturer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddStationeryLayout.createSequentialGroup()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanelAddStationeryLayout.setVerticalGroup(
            jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddStationeryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEnterStationeryDetails)
                .addGap(18, 18, 18)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStationeryID)
                    .addComponent(jLabelQuantity)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStationeryID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStoreLocation)
                    .addComponent(jTextFieldStoreLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManufacturer)
                    .addComponent(jTextFieldManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanelAddStationeryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPaneAddSTLayout = new javax.swing.GroupLayout(jPaneAddST);
        jPaneAddST.setLayout(jPaneAddSTLayout);
        jPaneAddSTLayout.setHorizontalGroup(
            jPaneAddSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneAddSTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddStationery, javax.swing.GroupLayout.PREFERRED_SIZE, 856, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneAddSTLayout.setVerticalGroup(
            jPaneAddSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneAddSTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddStationery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneAddST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneAddST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        Stationery st = new Stationery(Integer.valueOf(jTextFieldStationeryID.getText()), jTextFieldName.getText(), Integer.valueOf(jTextFieldQuantity.getText()), Float.valueOf(jTextFieldPrice.getText()), jTextFieldStoreLocation.getText(), jTextFieldType.getText(), jTextFieldManufacturer.getText());
        if(st.addSt()) {
            JOptionPane.showMessageDialog(rootPane, "Successefully added new Stationery", "Added a new stationery", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(rootPane, "Failed to add a new stationery", "Failed new stationery", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        FunctionForm form = new FunctionForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStationeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStationeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStationeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStationeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStationeryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelEnterStationeryDetails;
    private javax.swing.JLabel jLabelManufacturer;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStationeryID;
    private javax.swing.JLabel jLabelStoreLocation;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPaneAddST;
    private javax.swing.JPanel jPanelAddStationery;
    private javax.swing.JTextField jTextFieldManufacturer;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldStationeryID;
    private javax.swing.JTextField jTextFieldStoreLocation;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
