/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp;

import javax.swing.JFrame;

/**
 *
 * @author Vicky
 */
public class DeleteItemForm extends javax.swing.JFrame {
    private String type;
    /**
     * Creates new form DeleteItemForm
     */
    public DeleteItemForm(String type) {
        initComponents();
        this.type=type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDeleteItem = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelDeleteItem = new javax.swing.JLabel();
        jLabelItemID = new javax.swing.JLabel();
        jTextFieldItemID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDeleteItem.setBackground(new java.awt.Color(0, 0, 0));

        jButtonDelete.setBackground(new java.awt.Color(0, 255, 255));
        jButtonDelete.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(255, 102, 51));
        jButtonBack.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelDeleteItem.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelDeleteItem.setForeground(new java.awt.Color(255, 255, 0));
        jLabelDeleteItem.setText("Delete Item");

        jLabelItemID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelItemID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemID.setText("Item ID : ");

        jTextFieldItemID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanelDeleteItemLayout = new javax.swing.GroupLayout(jPanelDeleteItem);
        jPanelDeleteItem.setLayout(jPanelDeleteItemLayout);
        jPanelDeleteItemLayout.setHorizontalGroup(
            jPanelDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDeleteItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDeleteItemLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDeleteItemLayout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanelDeleteItemLayout.createSequentialGroup()
                        .addComponent(jLabelItemID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItemID)
                        .addGap(59, 59, 59))))
        );
        jPanelDeleteItemLayout.setVerticalGroup(
            jPanelDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeleteItemLayout.createSequentialGroup()
                .addComponent(jLabelDeleteItem)
                .addGap(34, 34, 34)
                .addGroup(jPanelDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelItemID)
                    .addComponent(jTextFieldItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanelDeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
         if(type.equalsIgnoreCase("book")) {
            Book book = new Book();
            book.deleteBook(Integer.valueOf(jTextFieldItemID.getText()));
        }else if(type.equalsIgnoreCase("stationery")){
            Stationery st= new Stationery();
            st.deleteSt(Integer.valueOf(jTextFieldItemID.getText()));
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        FunctionForm form = new FunctionForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabelDeleteItem;
    private javax.swing.JLabel jLabelItemID;
    private javax.swing.JPanel jPanelDeleteItem;
    private javax.swing.JTextField jTextFieldItemID;
    // End of variables declaration//GEN-END:variables
}
