/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp;

import javax.swing.JFrame;

/**
 *
 * @author Vicky
 */
public class FunctionForm extends javax.swing.JFrame {
    private String type;
    /**
     * Creates new form FunctionForm
     */
    public FunctionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFunction = new javax.swing.JPanel();
        jLabelInventoryFunction = new javax.swing.JLabel();
        jButtonViewInventory = new javax.swing.JButton();
        jButtonSearchItem = new javax.swing.JButton();
        jButtonAddItem = new javax.swing.JButton();
        jButtonMoveItem = new javax.swing.JButton();
        jButtonDeleteItem = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jMenuBarItemType = new javax.swing.JMenuBar();
        jMenuItemType = new javax.swing.JMenu();
        jMenuItemBook = new javax.swing.JMenuItem();
        jMenuItemStationery = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFunction.setBackground(new java.awt.Color(0, 0, 0));

        jLabelInventoryFunction.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelInventoryFunction.setForeground(new java.awt.Color(255, 102, 51));
        jLabelInventoryFunction.setText("Select Inventory Function :");

        jButtonViewInventory.setBackground(new java.awt.Color(204, 204, 0));
        jButtonViewInventory.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonViewInventory.setText("View Inventory");
        jButtonViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewInventoryActionPerformed(evt);
            }
        });

        jButtonSearchItem.setBackground(new java.awt.Color(102, 255, 102));
        jButtonSearchItem.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonSearchItem.setText("Search Item ");
        jButtonSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchItemActionPerformed(evt);
            }
        });

        jButtonAddItem.setBackground(new java.awt.Color(255, 51, 255));
        jButtonAddItem.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonAddItem.setText("Add Item");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jButtonMoveItem.setBackground(new java.awt.Color(51, 51, 255));
        jButtonMoveItem.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonMoveItem.setText("Move Item");
        jButtonMoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveItemActionPerformed(evt);
            }
        });

        jButtonDeleteItem.setBackground(new java.awt.Color(255, 0, 51));
        jButtonDeleteItem.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonDeleteItem.setText("Delete Item");
        jButtonDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteItemActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExit.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFunctionLayout = new javax.swing.GroupLayout(jPanelFunction);
        jPanelFunction.setLayout(jPanelFunctionLayout);
        jPanelFunctionLayout.setHorizontalGroup(
            jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFunctionLayout.createSequentialGroup()
                        .addComponent(jButtonMoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanelFunctionLayout.createSequentialGroup()
                        .addComponent(jButtonViewInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelFunctionLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabelInventoryFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFunctionLayout.setVerticalGroup(
            jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunctionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelInventoryFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jMenuItemType.setBackground(new java.awt.Color(0, 0, 153));
        jMenuItemType.setText("Select Item Type");
        jMenuItemType.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jMenuItemBook.setBackground(new java.awt.Color(0, 204, 255));
        jMenuItemBook.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jMenuItemBook.setText("Book");
        jMenuItemBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookActionPerformed(evt);
            }
        });
        jMenuItemType.add(jMenuItemBook);

        jMenuItemStationery.setBackground(new java.awt.Color(0, 204, 255));
        jMenuItemStationery.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jMenuItemStationery.setText("Stationery");
        jMenuItemStationery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStationeryActionPerformed(evt);
            }
        });
        jMenuItemType.add(jMenuItemStationery);

        jMenuBarItemType.add(jMenuItemType);

        setJMenuBar(jMenuBarItemType);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
         if(type.equalsIgnoreCase("book")) {
            AddBookForm form = new AddBookForm();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else{
            AddStationeryForm form = new AddStationeryForm();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jMenuItemBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookActionPerformed
       type = "book";
    }//GEN-LAST:event_jMenuItemBookActionPerformed

    private void jMenuItemStationeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStationeryActionPerformed
        type = "stationery";
    }//GEN-LAST:event_jMenuItemStationeryActionPerformed

    private void jButtonViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewInventoryActionPerformed
        if(type.equalsIgnoreCase("book")) {
            BookViewInventoryForm form = new BookViewInventoryForm();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else{
            STViewInventoryForm form = new STViewInventoryForm();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButtonViewInventoryActionPerformed

    private void jButtonSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchItemActionPerformed
        Item item;
        if(type.equalsIgnoreCase("book")) item = new Book();
        else item = new Stationery();
        SearchItemForm form = new SearchItemForm(item);
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonSearchItemActionPerformed

    private void jButtonDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteItemActionPerformed
        DeleteItemForm form = new DeleteItemForm(type);
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  
    }//GEN-LAST:event_jButtonDeleteItemActionPerformed

    private void jButtonMoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveItemActionPerformed
        MoveItemForm form = new MoveItemForm(type);
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);   
    }//GEN-LAST:event_jButtonMoveItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunctionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonDeleteItem;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMoveItem;
    private javax.swing.JButton jButtonSearchItem;
    private javax.swing.JButton jButtonViewInventory;
    private javax.swing.JLabel jLabelInventoryFunction;
    private javax.swing.JMenuBar jMenuBarItemType;
    private javax.swing.JMenuItem jMenuItemBook;
    private javax.swing.JMenuItem jMenuItemStationery;
    private javax.swing.JMenu jMenuItemType;
    private javax.swing.JPanel jPanelFunction;
    // End of variables declaration//GEN-END:variables
}
