/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vicky
 */
public class MoveItemForm extends javax.swing.JFrame {
       private String type;
    /**
     * Creates new form MoveItemForm
     */
    public MoveItemForm(String type) {
        initComponents();
        this.type = type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSearchItem = new javax.swing.JPanel();
        jLabelMoveItem = new javax.swing.JLabel();
        jLabelItemID = new javax.swing.JLabel();
        jTextFieldIdSearch = new javax.swing.JTextField();
        jScrollPaneItem = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabeMoveTo = new javax.swing.JLabel();
        jTextFieldNewLocation = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSearchItem.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMoveItem.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelMoveItem.setForeground(new java.awt.Color(255, 255, 0));
        jLabelMoveItem.setText("Move Item");

        jLabelItemID.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelItemID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemID.setText("Item ID : ");

        jTextFieldIdSearch.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneItem.setViewportView(jTableItem);

        jButtonBack.setBackground(new java.awt.Color(153, 0, 0));
        jButtonBack.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 51, 51));
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabeMoveTo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabeMoveTo.setForeground(new java.awt.Color(255, 255, 255));
        jLabeMoveTo.setText("Move To  : ");

        jTextFieldNewLocation.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jButtonSearch.setBackground(new java.awt.Color(0, 51, 204));
        jButtonSearch.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(0, 204, 204));
        jButtonSearch.setText("SEARCH");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonEnter.setBackground(new java.awt.Color(51, 153, 0));
        jButtonEnter.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(0, 255, 0));
        jButtonEnter.setText("ENTER");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchItemLayout = new javax.swing.GroupLayout(jPanelSearchItem);
        jPanelSearchItem.setLayout(jPanelSearchItemLayout);
        jPanelSearchItemLayout.setHorizontalGroup(
            jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneItem)
                            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                        .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMoveItem))
                            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabelItemID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabeMoveTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNewLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchItemLayout.createSequentialGroup()
                    .addContainerGap(347, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(320, 320, 320)))
        );
        jPanelSearchItemLayout.setVerticalGroup(
            jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMoveItem)
                .addGap(30, 30, 30)
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelItemID)
                    .addComponent(jTextFieldIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeMoveTo)
                    .addComponent(jTextFieldNewLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchItemLayout.createSequentialGroup()
                    .addContainerGap(275, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(139, 139, 139)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
                FunctionForm form = new FunctionForm();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        if(type.equalsIgnoreCase("book")) {
            Book book = new Book();
            book.searchBookById(jTableItem, Integer.valueOf(jTextFieldIdSearch.getText()));
        } else {
            Stationery st = new Stationery();
            st.searchBookById(jTableItem, Integer.valueOf(jTextFieldIdSearch.getText()));
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
       if(type.equalsIgnoreCase("book")) {
           Book book = new Book();
            if(book.moveBook(Integer.valueOf(jTextFieldIdSearch.getText()),jTextFieldNewLocation.getText())) {
               JOptionPane.showMessageDialog(rootPane, "Moved to new location!", "Success!", JOptionPane.ERROR_MESSAGE);
            }
       } else {
           Stationery st = new Stationery();
           if(st.moveSt(Integer.valueOf(jTextFieldIdSearch.getText()),jTextFieldNewLocation.getText())) {
               JOptionPane.showMessageDialog(rootPane, "Moved to new location!", "Success!", JOptionPane.ERROR_MESSAGE);
           }
       }
       
       
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MoveItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MoveItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MoveItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MoveItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MoveItemForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabeMoveTo;
    private javax.swing.JLabel jLabelItemID;
    private javax.swing.JLabel jLabelMoveItem;
    private javax.swing.JPanel jPanelSearchItem;
    private javax.swing.JScrollPane jScrollPaneItem;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTextField jTextFieldIdSearch;
    private javax.swing.JTextField jTextFieldNewLocation;
    // End of variables declaration//GEN-END:variables
}
