/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vicky
 */
public class SearchItemForm extends javax.swing.JFrame {
    private Item item;
    /**
     * Creates new form SearchItemForm
     */
    public SearchItemForm(Item item) {
        initComponents();
        this.item = item;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSearchItem = new javax.swing.JPanel();
        jLabelSearchItem = new javax.swing.JLabel();
        jLabelKeyword = new javax.swing.JLabel();
        jTextFieldKeywordSearch = new javax.swing.JTextField();
        jScrollPaneItem = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabelSubtractQuantity = new javax.swing.JLabel();
        jTextFieldSubtractQty = new javax.swing.JTextField();
        jLabelAddQuantity = new javax.swing.JLabel();
        jTextFieldAddQuantity = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSearchItem.setBackground(new java.awt.Color(0, 0, 0));

        jLabelSearchItem.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelSearchItem.setForeground(new java.awt.Color(255, 255, 0));
        jLabelSearchItem.setText("Search Item");

        jLabelKeyword.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelKeyword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKeyword.setText("Keyword : ");

        jTextFieldKeywordSearch.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneItem.setViewportView(jTableItem);

        jButtonBack.setBackground(new java.awt.Color(255, 0, 51));
        jButtonBack.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelSubtractQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelSubtractQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtractQuantity.setText("Subtract Quantity : ");

        jTextFieldSubtractQty.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jLabelAddQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelAddQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddQuantity.setText("Add Quantity : ");

        jTextFieldAddQuantity.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N

        jButtonSearch.setBackground(new java.awt.Color(0, 51, 204));
        jButtonSearch.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(0, 204, 204));
        jButtonSearch.setText("SEARCH");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonEnter.setBackground(new java.awt.Color(51, 255, 0));
        jButtonEnter.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jButtonEnter.setText("ENTER");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchItemLayout = new javax.swing.GroupLayout(jPanelSearchItem);
        jPanelSearchItem.setLayout(jPanelSearchItemLayout);
        jPanelSearchItemLayout.setHorizontalGroup(
            jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSearchItem))
                    .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelKeyword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldKeywordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                        .addComponent(jScrollPaneItem)
                        .addContainerGap())
                    .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                        .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAddQuantity)
                            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAddQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSubtractQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSubtractQty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchItemLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchItemLayout.createSequentialGroup()
                    .addContainerGap(347, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(320, 320, 320)))
        );
        jPanelSearchItemLayout.setVerticalGroup(
            jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSearchItem)
                .addGap(30, 30, 30)
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKeyword)
                    .addComponent(jTextFieldKeywordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubtractQuantity)
                    .addComponent(jTextFieldSubtractQty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddQuantity))
                .addGap(35, 35, 35)
                .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelSearchItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchItemLayout.createSequentialGroup()
                    .addContainerGap(275, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(139, 139, 139)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        DefaultTableModel table = (DefaultTableModel) jTableItem.getModel();
        int rIndex = jTableItem.getSelectedRow();
        int value = Integer.valueOf(jTextFieldAddQuantity.getText());
        int id = Integer.valueOf(table.getValueAt(rIndex, 0).toString());
        if(rIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please click the data first", "No data", JOptionPane.WARNING_MESSAGE);
        } else {
            if(jTextFieldSubtractQty.getText().equals("")) {
                if(item instanceof Book) {
                    if(((Book) item).addQuantiy(id, value)) {
                        System.out.println("Ys");
                    } else {
                        System.out.println("errr");
                    }
                } else {
                    if (((Stationery) item).addQuantiy(id, value)) {
                        System.out.println("tes");
                    }
                }
            } else if(jTextFieldAddQuantity.getText().equals("")) {
                if(item instanceof Book) {
                    if(((Book) item).subQuantity(id, value)) {
                        System.out.println("Ys");
                    } else {
                        System.out.println("No");
                    }
                } else {
                    if (((Stationery) item).subQuantity(id, value)) {
                        System.out.println("tes");
                    }
                }
            }
        }
        initTable();
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void initTable() {
        jTableItem.setModel(new DefaultTableModel(null, new Object[]{"Id", "Name", "quantity", "price(RM)"}) {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
        }});
    }
    
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
                FunctionForm form = new FunctionForm();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        if(item instanceof Book) {
            ((Book)item).searchBook(jTableItem, jTextFieldKeywordSearch.getText());
        } else {
            ((Stationery)item).searchSt(jTableItem, jTextFieldKeywordSearch.getText());
        }
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchItemForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelAddQuantity;
    private javax.swing.JLabel jLabelKeyword;
    private javax.swing.JLabel jLabelSearchItem;
    private javax.swing.JLabel jLabelSubtractQuantity;
    private javax.swing.JPanel jPanelSearchItem;
    private javax.swing.JScrollPane jScrollPaneItem;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTextField jTextFieldAddQuantity;
    private javax.swing.JTextField jTextFieldKeywordSearch;
    private javax.swing.JTextField jTextFieldSubtractQty;
    // End of variables declaration//GEN-END:variables
}
